### ISSUE TITLE
Problems with sequences

### ISSUE THREAD

**Issue by hectoralos** [apertium/apertium-lex-tools#93]
I have these rules:

```
  <rule weight="0.8">
    <match lemma="per" tags="pr"><select lemma="pour"/></match>
  </rule>
  <rule weight="1.0">
    <match lemma="per" tags="pr"><select lemma="par"/></match>
    <or>
      <seq n="temps"/>
      <match lemma="eurò" tags="n.*"/>
      <match lemma="euro" tags="n.*"/>
```
etc.

Sequence "temps" is as follows:

```
    <def-seq n="temps">
      <match lemma="segonda" tags="n.*"/>
      <match lemma="minuta" tags="n.*"/>
      <match lemma="ora" tags="n.*"/>
      <match lemma="jorn" tags="n.*"/>
      <match lemma="setmana" tags="n.*"/>
      <match lemma="mes" tags="n.*"/>
      <match lemma="annada" tags="n.*"/>
      <match lemma="lustre" tags="n.*"/>
      <match lemma="decada" tags="n.*"/>
      <match lemma="sègle" tags="n.*"/>
      <match lemma="millenari" tags="n.*"/>
    </def-seq>
```

But I get:
```
$ echo "per mes" | apertium -d . oci-fra-lextor
2:SELECT:0.8:per<pr>:2:pour<pr>
^per<pr>/pour<pr>$ ^mes<n><m><sg>/mois<n><m><sp>$^.<sent>/.<sent>$
$ echo "per eurò" | apertium -d . oci-fra-lextor
2:SELECT:1:per<pr>:2:par<pr>
^per<pr>/par<pr>$ ^eurò<n><m><sg>/euro<n><m><sg>$^.<sent>/.<sent>$
```

For some reason, now "mes", which is in the sequence, is not taken into account. It worked a few days ago.

**Comment by mr-martian** [comment]
Make it `<def-seq> <or> <match> <match> ... </or> </def-seq>` and then it will work as it did before.

With metalrx, `<seq>` meant "copy and paste these things in this spot in the file" where as in lrx it means "insert these things at this point in the transducer". These should be equivalent in all situations except this one, though since having an `<or>` inside an `<or>` is fine, it's pretty easy to fix.

**Comment by hectoralos** [comment]
Ok, if I add <or>...</or> in the <def-seq> it works. Is this change really necessary? I will need to go through several language pairs. And many other developers will have the same problem. This kind of changes should be announced in the mailing list.

**Comment by mr-martian** [comment]
The change was made because exactly replicating the old behavior was not a feasible change. The issue was discussed in #33 and #34.

It looks like it affects approximately this many places in the following files:

```
     31 ./apertium-cat-ita/apertium-cat-ita.cat-ita.metalrx
      9 ./apertium-cat-ita/apertium-cat-ita.ita-cat.metalrx
     21 ./apertium-cat-srd/apertium-cat-srd.cat-srd.metalrx
     15 ./apertium-fra-cat/apertium-fra-cat.cat-fra.metalrx
     15 ./apertium-fra-cat/apertium-fra-cat.fra-cat.metalrx
      8 ./apertium-oci-fra/apertium-oci-fra.fra-oci.metalrx
      3 ./apertium-oci-fra/apertium-oci-fra.oci-fra.metalrx
     32 ./apertium-por-cat/apertium-por-cat.cat-por.metalrx
      3 ./apertium-por-cat/apertium-por-cat.por-cat.metalrx
     23 ./apertium-spa-cat/apertium-spa-cat.cat-spa.metalrx
```

As long as pairs continue to use `metalrx-to-lrx`, they don't need to change, it's only if there's some reason to switch that someone has to check this.

When I implemented `<def-seq>` in `lrx-comp`, I offered to update all the existing files, and I could do that tonight so that we don't run into this issue again.
